

server:
  port: 9977
spring:
  application:
    name: api-gateway

  zipkin:
    base-url: http://localhost:9411

  cloud:
    gateway:
      routes:
           - id: client
             uri: lb://CLIENT
             predicates:
                   - Path=/api/v1/client/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7777/eureka

